### ISSUE TITLE
Can't get Mautibox working on Elastic Beanstalk

### ISSUE THREAD

**Issue by dennisameling** [mautibox/mautibox#8]
I can't seem to get a working Mautibox on a fresh Elastic Beanstalk environment.

I used this config (didn't choose `Amazon Linux 2` on purpose because it caused all sorts of trouble):

![image](https://user-images.githubusercontent.com/17739158/90252023-1384d600-de3f-11ea-8c44-bc875f762c7d.png)

However, in the logs it said that I needed the `php-imap` extension. So I added the following to `build.sh` and `stage.sh`:

`sudo yum -y install php73-imap`

That got me partly up and running. Only thing that's left is that the API endpoint `/api/pulls/` doesn't work:

![image](https://user-images.githubusercontent.com/17739158/90252089-33b49500-de3f-11ea-8c34-d378cb478629.png)

This is shown in the network logs of the browser:

```
<br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined function Cache\Adapter\Apcu\apcu_fetch() in /var/app/current/vendor/cache/apcu-adapter/ApcuCachePool.php:48
Stack trace:
#0 /var/app/current/vendor/cache/adapter-common/AbstractCachePool.php(133): Cache\Adapter\Apcu\ApcuCachePool-&gt;fetchObjectFromCache('mautic_pulls')
#1 /var/app/current/vendor/cache/adapter-common/CacheItem.php(245): Cache\Adapter\Common\AbstractCachePool-&gt;Cache\Adapter\Common\{closure}()
#2 /var/app/current/vendor/cache/adapter-common/CacheItem.php(116): Cache\Adapter\Common\CacheItem-&gt;initialize()
#3 /var/app/current/vendor/cache/adapter-common/AbstractCachePool.php(429): Cache\Adapter\Common\CacheItem-&gt;isHit()
#4 /var/app/current/web/api/pulls/index.php(8): Cache\Adapter\Common\AbstractCachePool-&gt;get('mautic_pulls')
#5 {main}
  thrown in <b>/var/app/current/vendor/cache/apcu-adapter/ApcuCachePool.php</b> on line <b>48</b><br />
```

I tried things like `pecl install apcu` but it didn't get me up and running, unfortunately.

Am I missing something? I believe `apcu_fetch()` is rather old and might need to be replaced. I'm happy to help and provide a PR to get this working on fresh Beanstalk instances, let me know 😊

**Comment by heathdutton** [comment]
We have not upgraded past minimum PHP compatibility of Mautic.
So, I'm currently running mautibox on: PHP 7.2 running on 64bit Amazon Linux/2.9.7 (overdue for an upgrade)
With a single instance: t3a.medium (Occasionally I go up to a much larger tier when there is heavy testing)
Mounted: 100GB SSD

Note, you also need to fill in the envvars:
APP_URL = (url to your instance)
GH_TOKEN = (github token for accessing PRs)
STAGING_BRANCH = staging

Note: APCu is still (remarkably) a valid and capable caching mechanism. It's just a memory-based key/value storage (opcache now handles bytecode). In my perf tests it easily beats anything else with this class of application when running on a single instance. I want to make sure APCu is available to be sure we are still testing it because it gives single-instance Mautic installs a noticeable performance boost with virtually no cost and APCu is still often included by default.

**Comment by dennisameling** [comment]
Okay, I'll test a bit more over the weekend and will provide a PR if I find how to get APCu working in Beanstalk 😊 thanks!
